[package]
name = "xauth-captcha"
version = "0.1.2"
description = "A lightweight, robust, and dependency-minimal CAPTCHA generation library for Rust"
license-file = "LICENSE"
authors = ["Serhii Cherneha"]
edition = "2024"

[dependencies]
image = "0.25.10"
rand = "0.10.2"
rusttype = "0.9.3"
serde = { version = "1.0.229", features = ["derive"] }
